### ISSUE TITLE
Virus Trojan.Cerbu & Trojan.Agent

### ISSUE THREAD

**Issue by nongdancryptos** [Jaammerr/Gradient-Network-Bot#4]
https://www.virustotal.com/gui/file/4644dc69ce4988bba0e75f40ce8e0c3815341b9fe055680921842630859d23ae?nocache=1
![image](https://github.com/user-attachments/assets/1269c2ec-a819-4951-aa72-f17007260cda)

**Comment by Jaammerr** [comment]
Bro, first google these so-called trojans. They will be on all EXEs without a license. This is normal

Read more here: https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

**Comment by Jaammerr** [comment]
And if there really was a trojan there, then this repository would have been deleted long ago :D
